# Tree Search для игр

In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

import numpy as np
import matplotlib.pyplot as plt

## Крестики-нолики

In [2]:
from game import TicTacToe

tic_tac_toe = TicTacToe()

start_state = tic_tac_toe.start()
print(start_state)

_|_|_
_|_|_
_|_|_


In [3]:
# 1-based index of current player
tic_tac_toe.turn

np.int64(1)

In [4]:
start_state.actions

[[0, 0], [0, 1], [0, 2], [1, 0], [1, 1], [1, 2], [2, 0], [2, 1], [2, 2]]

In [5]:
from agent.player import IOPlayer, RandomPlayer
from game.manager import GameManager

io_player = IOPlayer(from_str='list[int]')
random_player = RandomPlayer()

manager = GameManager(tic_tac_toe, io_player, random_player)
manager.run_single_game()

You win!
Final state:
x|o|_
_|x|_
o|_|x


np.int64(1)

In [6]:
from agent.player import BFSPlayer


bfs_player = BFSPlayer(2)

manager = GameManager(TicTacToe(), io_player, bfs_player)
manager.run_single_game()

You win!
Final state:
x|o|_
x|x|_
x|o|o


np.int64(1)

In [7]:
manager = GameManager(TicTacToe(), bfs_player, io_player)
manager.run_single_game()

It`s a draw.
Final state:
x|o|x
o|o|x
x|x|o


In [8]:
n_plays = 10000
manager = GameManager(TicTacToe(), RandomPlayer(), RandomPlayer(), n_plays=n_plays)
results = manager.run(verbose=True)
results

  0%|          | 0/10000 [00:00<?, ?it/s]

{'winners (players)': array([1, 1, 1, ..., 0, 1, 1], shape=(10000,)),
 'winners (roles)': array([1, 1, 1, ..., 0, 1, 1], shape=(10000,)),
 'winners matrix': array([[1280.,    0.,    0.],
        [   0., 5880.,    0.],
        [   0.,    0., 2840.]])}

In [9]:
win_counts = np.unique_counts(results["winners (roles)"]).counts
win_counts / n_plays

array([0.128, 0.588, 0.284])

In [10]:
n_plays = 1000
manager = GameManager(TicTacToe(), BFSPlayer(1), RandomPlayer(), n_plays=n_plays, shuffling='circular')
results = manager.run(verbose=True)
results["winners matrix"]

  0%|          | 0/1000 [00:00<?, ?it/s]

array([[ 69.,   0.,   0.],
       [  0., 410., 194.],
       [  0., 269.,  58.]])

In [11]:
n_plays = 1000
manager = GameManager(TicTacToe(), BFSPlayer(2), RandomPlayer(), n_plays=n_plays, shuffling='circular')
results = manager.run(verbose=True)
results["winners matrix"]

  0%|          | 0/1000 [00:00<?, ?it/s]

array([[163.,   0.,   0.],
       [  0., 440.,  35.],
       [  0., 356.,   6.]])

In [12]:
n_plays = 1000
manager = GameManager(TicTacToe(), BFSPlayer(1), BFSPlayer(1), n_plays=n_plays, shuffling='circular')
results = manager.run(verbose=True)
results["winners matrix"]

  0%|          | 0/1000 [00:00<?, ?it/s]

array([[ 43.,   0.,   0.],
       [  0., 331., 336.],
       [  0., 141., 149.]])

In [13]:
n_plays = 1000
manager = GameManager(TicTacToe(), BFSPlayer(2), BFSPlayer(1), n_plays=n_plays, shuffling='circular')
results = manager.run(verbose=True)
results["winners matrix"]

  0%|          | 0/1000 [00:00<?, ?it/s]

array([[149.,   0.,   0.],
       [  0., 440.,  66.],
       [  0., 328.,  17.]])

In [14]:
n_plays = 1000
manager = GameManager(TicTacToe(), BFSPlayer(2), BFSPlayer(2), n_plays=n_plays, shuffling='circular')
results = manager.run(verbose=True)
results["winners matrix"]

  0%|          | 0/1000 [00:00<?, ?it/s]

array([[529.,   0.,   0.],
       [  0., 151., 158.],
       [  0.,  83.,  79.]])

In [15]:
n_plays = 1000
manager = GameManager(TicTacToe(), BFSPlayer(3), RandomPlayer(), n_plays=n_plays, shuffling='circular')
results = manager.run(verbose=True)
results["winners matrix"]

  0%|          | 0/1000 [00:00<?, ?it/s]

array([[108.,   0.,   0.],
       [  0., 475.,  53.],
       [  0., 359.,   5.]])

In [16]:
manager = GameManager(TicTacToe(), io_player, BFSPlayer(5))
manager.run_single_game()

It`s a draw.
Final state:
o|o|x
x|x|o
o|x|x


In [17]:
manager = GameManager(TicTacToe(), BFSPlayer(5), io_player)
manager.run_single_game()

You are lose :(
Final state:
x|x|x
o|o|_
x|_|o


np.int64(1)

In [18]:
from agent.player import DFSPlayer

ts = DFSPlayer(verbose=True)

In [19]:
tic_tac_toe = TicTacToe()
ts.fit(tic_tac_toe)

Found 10 states.
Found 100 states.
Found 1000 states.
Found 5478 states in total.


In [20]:
manager = GameManager(TicTacToe(), io_player, ts)
manager.run_single_game()

It`s a draw.
Final state:
x|o|o
o|x|x
x|x|o


In [27]:
manager = GameManager(TicTacToe(), ts, io_player)
manager.run_single_game()

It`s a draw.
Final state:
o|x|o
x|o|x
x|o|x


In [28]:
manager = GameManager(TicTacToe(), ts, RandomPlayer(), n_plays=100, shuffling='circular')
results = manager.run(verbose=True)
results["winners matrix"]

  0%|          | 0/100 [00:00<?, ?it/s]

array([[ 9.,  0.,  0.],
       [ 0., 49.,  0.],
       [ 0., 42.,  0.]])

In [29]:
manager = GameManager(TicTacToe(), ts, BFSPlayer(1), n_plays=100, shuffling='circular')
results = manager.run(verbose=True)
results["winners matrix"]

  0%|          | 0/100 [00:00<?, ?it/s]

array([[13.,  0.,  0.],
       [ 0., 50.,  0.],
       [ 0., 37.,  0.]])

In [30]:
manager = GameManager(TicTacToe(), ts, BFSPlayer(2), n_plays=100, shuffling='circular')
results = manager.run(verbose=True)
results["winners matrix"]

  0%|          | 0/100 [00:00<?, ?it/s]

array([[55.,  0.,  0.],
       [ 0., 39.,  0.],
       [ 0.,  6.,  0.]])

In [31]:
manager = GameManager(TicTacToe(), ts, BFSPlayer(3), n_plays=100, shuffling='circular')
results = manager.run(verbose=True)
results["winners matrix"]

  0%|          | 0/100 [00:00<?, ?it/s]

array([[53.,  0.,  0.],
       [ 0., 36.,  0.],
       [ 0., 11.,  0.]])

In [32]:
manager = GameManager(TicTacToe(), ts, ts, n_plays=100, shuffling='circular')
results = manager.run(verbose=True)
results["winners matrix"]

  0%|          | 0/100 [00:00<?, ?it/s]

array([[100.,   0.,   0.],
       [  0.,   0.,   0.],
       [  0.,   0.,   0.]])

## Connect Four

In [33]:
from game import ConnectFour

connect_four = ConnectFour()
print(connect_four.start())

 0 1 2 3 4 5 6 
 v v v v v v v 
| | | | | | | |
| | | | | | | |
| | | | | | | |
| | | | | | | |
| | | | | | | |
|_|_|_|_|_|_|_|



In [34]:
connect_four.start().actions

[0, 1, 2, 3, 4, 5, 6]

In [35]:
manager = GameManager(ConnectFour(), IOPlayer(from_str=int), BFSPlayer(4))
manager.run_single_game()

You win!
Final state:
 0 1 2 3 4 5 6 
 v v v v v v v 
| | | |x| | | |
| |o| |x| |x| |
| |x| |o| |o| |
| |o|o|x| |x| |
|o|x|x|x|x|o|x|
|o|o|x|x|o|o|o|



np.int64(1)

In [36]:
manager = GameManager(ConnectFour(), BFSPlayer(4), IOPlayer(from_str=int))
manager.run_single_game()

You win!
Final state:
 0 1 2 3 4 5 6 
 v v v v v v v 
| |o| |o|o| |o|
| |x| |o|x| |o|
| |o| |x|x| |x|
| |o|o|o|o| |o|
|x|o|x|o|x| |x|
|x|x|x|o|x|x|x|



np.int64(2)

In [37]:
manager = GameManager(ConnectFour(), RandomPlayer(), RandomPlayer(), n_plays=1000)
results = manager.run(verbose=True)
results["winners matrix"]

  0%|          | 0/1000 [00:00<?, ?it/s]

array([[  2.,   0.,   0.],
       [  0., 522.,   0.],
       [  0.,   0., 476.]])

In [38]:
manager = GameManager(ConnectFour(), BFSPlayer(2), RandomPlayer(), n_plays=500, shuffling='circular')
results = manager.run(verbose=True)
results["winners matrix"]

  0%|          | 0/500 [00:00<?, ?it/s]

array([[  1.,   0.,   0.],
       [  0., 236.,  16.],
       [  0., 234.,  13.]])

In [39]:
manager = GameManager(ConnectFour(), BFSPlayer(2), BFSPlayer(2), n_plays=100)
results = manager.run(verbose=True)
results["winners matrix"]

  0%|          | 0/100 [00:00<?, ?it/s]

array([[12.,  0.,  0.],
       [ 0., 50.,  0.],
       [ 0.,  0., 38.]])

In [40]:
manager = GameManager(ConnectFour(), BFSPlayer(3), BFSPlayer(3), n_plays=50)
results = manager.run(verbose=True)
results["winners matrix"]

  0%|          | 0/50 [00:00<?, ?it/s]

array([[ 1.,  0.,  0.],
       [ 0., 28.,  0.],
       [ 0.,  0., 21.]])

In [41]:
manager = GameManager(ConnectFour(), BFSPlayer(4), BFSPlayer(4), n_plays=10)
results = manager.run(verbose=True)
results["winners matrix"]

  0%|          | 0/10 [00:00<?, ?it/s]

array([[1., 0., 0.],
       [0., 4., 0.],
       [0., 0., 5.]])